### ISSUE TITLE
Anonieme functie

### ISSUE THREAD

**Issue by rikmeijer** [Avans/Prog5#36]
Dit is een functie zonder naam, die maar 1 keer uitgevoerd wordt. <-- Technisch hoeft dat niet, je kunt ze prima meerdere keren uitvoeren. Het zijn eerder 'throw away' functies ofzo...

**Comment by Linksonder** [comment]
Wat doet deze expressie nu eigenlijk? Als je een lambda expressie defini&euml;ert, defini&euml;er je onder water een 'anonieme' functie. 
                    Dit is een functie zonder naam, die na het uitvoeren wordt weggegooid.
